name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta el workflow diariamente
  push: {}
  pull_request: {}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_message: "[metrics] update metrics"
          committer_branch: metrics

          # Configuración básica para mostrar logros
          plugin_achievements: true
