name: Metrics
on:
  schedule:
    - cron: "50 * * * *"  # Ejecuta el workflow diariamente
  push: {}
  pull_request: {}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 1000
          retries: 10
          repositories_affiliations: owner, collaborator
          base: ""
          output_action: commit
          committer_message: "[metrics] update metrics"
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          config_timezone: America/Los_Angeles
          config_display: columns
          committer_branch: metrics

          # Configuración para mostrar solo logros
          plugin_isocalendar: no
          plugin_calendar: no
          plugin_achievements: true
          plugin_achievements_ignored: automater, stargazer, forker, gister  # Personaliza según los logros que quieres mostrar
          plugin_languages: no
          plugin_sponsors: no
