name: Metrics

on:
  schedule:
    # Corre a las 00:00 UTC todos los días
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_achievements_ignored: repository

